[project]
name = "database-ontology-mcp"
version = "0.1.0"
description = "MCP server for database schema analysis and ontology generation"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=0.9.0",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "snowflake-sqlalchemy>=1.5.0",
    "snowflake-connector-python>=3.0.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "rdflib>=7.0.0",
    "owlrl>=6.0.0",
    "openai>=1.3.0",
]

[project.urls]
Homepage = "https://github.com/yourusername/database-ontology-mcp"
Repository = "https://github.com/yourusername/database-ontology-mcp"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
]
